#Filters
Set-Alias -Name filter -Value 'C:\scripts\filter.ps1'
Set-Alias -Name f -Value 'C:\scripts\filter.ps1'
Set-Alias -Name powercat -Value 'C:\scripts\powercat.ps1'
Set-Alias -Name pcat -Value 'C:\scripts\powercat.ps1'

#Reverse Shells
Set-Alias -Name nc -Value 'C:\scripts\netcat\connect-ncat-rshell.ps1'
Set-Alias -Name ncc -Value 'C:\scripts\netcat\send-command.ps1'

#Linode
Set-Alias -Name node -Value 'C:\scripts\linode\connect-node.ps1'
Set-Alias -Name nd -Value 'C:\scripts\linode\connect-node.ps1'

#Base Helpers
Set-Alias -Name l -Value 'C:\scripts\list.ps1'
Set-Alias -Name vim -Value nvim
Set-Alias -Name accept-pipe -Value 'C:\scripts\accept-pipe.ps1'

#Firefox 
Set-Alias openfirefox -Value 'C:\Program Files\Mozilla Firefox\firefox.exe'
Set-Alias fire -Value 'C:\scripts\fire.ps1'
Set-Alias -Name firel -Value 'C:\scripts\firelucky.ps1'
Set-Alias -Name fil -Value 'C:\scripts\firelucky.ps1'

#Trento
Set-Alias -Name GetScarichiAnnullati -Value 'C:\Scripts\Selenium\GetReportScarichi\GetReportScarichi.ps1'
Set-Alias -Name gsa -Value 'C:\Scripts\Selenium\GetReportScarichi\GetReportScarichi.ps1'
Set-Alias -Name GetMissingSessions -Value 'C:\Scripts\Selenium\GetMissingSessions\GetMissingSessions.ps1'
Set-Alias -Name gms -Value 'C:\Scripts\Selenium\GetMissingSessions\GetMissingSessions.ps1'
Set-Alias -Name tncd -Value 'C:\Scripts\trento\rdp-trento\tncd.ps1'
Set-Alias -Name tnd -Value 'C:\Scripts\trento\deploy-update-valida.ps1'
Set-Alias -Name tndep -Value 'C:\Scripts\trento\deploy-update-valida.ps1'
Set-Alias -Name rcf -Value 'C:\Scripts\trento\trento-recupero-cf\recupero-defaults.ps1'
Set-Alias -Name rcfs -Value 'C:\Scripts\trento\trento-recupero-cf\recupero-stazioni.ps1'
Set-Alias -Name rcfa -Value 'C:\Scripts\trento\trento-recupero-cf\recupero-defaults-folder.ps1'
Set-Alias -Name get-trans-dates -Value 'C:\Scripts\trento\trento-trans-buster\get-trans-dates.ps1'
Set-Alias -Name get-date-correction -Value 'C:\Scripts\trento\trento-trans-buster\get-date-correction.ps1'
Set-Alias -Name tbuster -Value 'C:\Scripts\trento\trento-trans-buster\trans-buster.ps1'
Set-Alias -Name scarica-stazione -Value 'C:\Scripts\trento\scarica-stazione.ps1'
Set-Alias -Name sstaz -Value 'C:\Scripts\trento\scarica-stazione.ps1'
Set-Alias -Name tbus -Value 'C:\Scripts\trento\trento-trans-buster\trans-buster.ps1'
Set-Alias -Name fix-bus-codes -Value 'C:\Scripts\trento\trento-trans-buster\fix-bus-codes.ps1'
Set-Alias -Name remove-broken-lines -Value 'C:\Scripts\trento\trento-trans-buster\remove-broken-lines.ps1'
Set-Alias -Name trans-buster -Value 'C:\Scripts\trento\trento-trans-buster\trans-buster.ps1'
Set-Alias -Name rdp-concentratore -Value 'C:\Scripts\trento\rdp-trento\rdp-concentratore.ps1'
Set-Alias -Name rdpc -Value 'C:\Scripts\trento\rdp-trento\rdp-concentratore.ps1'
Set-Alias -Name trento -Value 'C:\Scripts\Trento\list-trento-commands.ps1'
Set-Alias -Name tn -Value 'C:\Scripts\Trento\list-trento-commands.ps1'

#RDP
Set-Alias -Name rdp -Value 'C:\scripts\trento\rdp-trento\rdp-trento.ps1'
Set-Alias -Name rdp147 -Value 'C:\scripts\trento\rdp147.ps1'
Set-Alias -Name rdp146 -Value 'C:\scripts\trento\rdp146.ps1'
Set-Alias -Name rdp-enter-ps-session -Value 'C:\scripts\trento\rdp-trento\rdp-enter-ps-session.ps1'
Set-Alias -Name rdpps -Value 'C:\scripts\trento\rdp-trento\rdp-enter-ps-session.ps1'

#Git
Set-Alias -Name commit -Value 'C:\scripts\commit.ps1'
Set-Alias -Name pull -Value 'C:\scripts\pull.ps1'
Set-Alias -Name newrepo -Value 'C:\scripts\gitCreateRepo.ps1'
Set-Alias -Name clonerepo -Value 'C:\scripts\clonerepo.ps1'
Set-Alias -Name github -Value 'C:\scripts\opengithub.ps1'
Set-Alias -Name p -Value 'C:\scripts\opengithub.ps1'
Set-Alias -Name opengitweb -Value Open-GitWeb
Set-Alias -Name opengit -Value Open-GitWeb
Set-Alias -Name ogit -Value Open-GitWeb
Set-Alias -Name ogw -Value Open-GitWeb

#Applications
Set-Alias -Name xy -Value 'C:\Program Files (x86)\XYplorer\XYplorer.exe'
Set-Alias -Name sublime -Value 'C:\Program Files\Sublime Text 3\sublime_text.exe'
Set-Alias -Name merge -Value 'C:\Program Files\WinMerge\WinMergeU.exe'
Set-Alias -Name vs -Value 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\devenv.exe'
Set-Alias -Name vscode -Value $user'\AppData\Local\Programs\Microsoft VS Code\Code.exe'
Set-Alias -Name vsc -Value $user'\AppData\Local\Programs\Microsoft VS Code\Code.exe'
Set-Alias -Name vpn -Value 'C:\Scripts\opennetworkconnect.ps1'
Set-Alias -Name revo -Value 'C:\Program Files\VS Revo Group\Revo Uninstaller\RevoUnin.exe'
Set-Alias -Name vault -Value 'C:\scripts\openvault.ps1'
Set-Alias -Name va -Value 'C:\scripts\openvault.ps1'
Set-Alias -Name obsidian -Value $user'\AppData\Local\Obsidian\Obsidian.exe'
Set-Alias -Name obsid -Value $user'\AppData\Local\Obsidian\Obsidian.exe'
Set-Alias -Name thunderbird -Value 'C:\Program Files\Mozilla Thunderbird\thunderbird.exe'
Set-Alias -Name cisco -Value 'C:\Program Files (x86)\Cisco\Cisco AnyConnect Secure Mobility Client\vpnui.exe'
Set-Alias -Name spotify -Value 'C:\Program Files\WindowsApps\SpotifyAB.SpotifyMusic_1.171.560.0_x86__zpdnekdrzrea0\Spotify.exe'
Set-Alias -Name spot -Value 'C:\Program Files\WindowsApps\SpotifyAB.SpotifyMusic_1.171.560.0_x86__zpdnekdrzrea0\Spotify.exe'
Set-Alias -Name photoshop -Value 'C:\Program Files\Adobe\Adobe Photoshop 2021\Photoshop.exe'
Set-Alias -Name phs -Value 'C:\Program Files\Adobe\Adobe Photoshop 2021\Photoshop.exe'
Set-Alias -Name illustrator -Value 'C:\Program Files\Adobe\Adobe Illustrator 2022\Support Files\Contents\Windows\Illustrator.exe'
Set-Alias -Name ill -Value 'C:\Program Files\Adobe\Adobe Illustrator 2022\Support Files\Contents\Windows\Illustrator.exe'
Set-Alias -Name il -Value 'C:\Program Files\Adobe\Adobe Illustrator 2022\Support Files\Contents\Windows\Illustrator.exe'
Set-Alias -Name premiere -Value 'C:\Program Files\Adobe\Adobe Premiere Pro 2022\Adobe Premiere Pro.exe'
Set-Alias -Name pr -Value 'C:\Program Files\Adobe\Adobe Premiere Pro 2022\Adobe Premiere Pro.exe'
Set-Alias -Name colorpicker -Value 'C:\Scripts\opencolorpicker.ps1'
Set-Alias -Name rstream -Value 'C:\Scripts\rstream.ps1'
Set-Alias -Name rainbowstream -Value 'C:\Scripts\rstream.ps1'
Set-Alias -Name twitter -Value 'C:\Scripts\rstream.ps1'
Set-Alias -Name tw -Value 'C:\Scripts\rstream.ps1'
Set-Alias -Name nmon -Value 'C:\Scripts\nmon.ps1'
Set-Alias -Name clock -Value 'C:\Scripts\clock.ps1'
Set-Alias -Name rtv -Value 'C:\Scripts\rtv\rtv.ps1'
Set-Alias -Name reddit -Value 'C:\Scripts\rtv\rtv.ps1'
Set-Alias -Name re -Value 'C:\Scripts\rtv\rtv.ps1'
Set-Alias -Name notflix -Value 'C:\Scripts\notflix.ps1'
Set-Alias -Name startup -Value 'C:\Scripts\open-startup.ps1'
Set-Alias -Name wp -Value 'C:\Scripts\whats-cli\whatscli.exe'
Set-Alias -Name ranger -Value 'C:\Scripts\ranger.ps1'
Set-Alias -Name lf -Value 'C:\Scripts\ranger.ps1'
Set-Alias -Name w -Value 'wsl'
Set-Alias -Name ol -Value 'c:\scripts\oneliners\oneliners.ps1'


#Application Downloads
Set-Alias -Name initPC -Value 'C:\scripts\appdownloads\initall.ps1'
Set-Alias -Name dlvscode -Value 'C:\scripts\appdownloads\dlvscode.ps1'


#Helpers
Set-Alias -Name h -Value Get-Help
Set-Alias -Name cl -Value 'C:\scripts\cclear.ps1'
Set-Alias -Name k -Value 'C:\scripts\cback.ps1'
Set-Alias -Name j -Value 'C:\scripts\cback.ps1'
Set-Alias -Name openproject -Value 'C:\scripts\openfirstsln.ps1'
Set-Alias -Name op -Value 'C:\scripts\openfirstsln.ps1'
Set-Alias -Name deletefolder -Value 'C:\scripts\deletecurrentfolder.ps1'
Set-Alias -Name df -Value 'C:\scripts\deletecurrentfolder.ps1'
Set-Alias -Name d -Value 'C:\scripts\delete.ps1'
Set-Alias -Name getfirstexerecursive -Value 'C:\scripts\getfirstexerecursive.ps1'
Set-Alias -Name getfirstexe -Value 'C:\scripts\getfirstexe.ps1'
Set-Alias -Name run -Value 'C:\scripts\runfirstexedebug.ps1'
Set-Alias -Name openall -Value 'C:\scripts\openall.ps1'
Set-Alias -Name reboot -Value 'C:\scripts\reboot.ps1'
Set-Alias -Name rb -Value 'C:\scripts\reboot.ps1'
Set-Alias -Name new -Value 'C:\scripts\newfile.ps1'
Set-Alias -Name o -Value 'C:\scripts\openfile.ps1'
Set-Alias -Name open -Value 'C:\scripts\openfile.ps1'
Set-Alias -Name GetMostRecentFile -Value 'C:\scripts\getmostrecentfile.ps1'
Set-Alias -Name RunMostRecentFile -Value 'C:\scripts\runmostrecentfile.ps1'
Set-Alias -Name runr -Value 'C:\scripts\runmostrecentfile.ps1'
Set-Alias -Name rr -Value 'C:\scripts\runmostrecentfile.ps1'
Set-Alias -Name openfile -Value 'C:\scripts\openfile.ps1'
Set-Alias -Name of -Value 'C:\scripts\openfile.ps1'
Set-Alias -Name ofr -Value 'C:\scripts\openfiler.ps1'
Set-Alias -Name newterminal -Value 'C:\scripts\nter.ps1'
Set-Alias -Name newter -Value 'C:\scripts\nter.ps1'
Set-Alias -Name nter -Value 'C:\scripts\nter.ps1'
Set-Alias -Name separator -Value 'C:\scripts\separator.ps1'
Set-Alias -Name organizebydatetime -Value 'C:\scripts\organizebydatetime.ps1'
Set-Alias -Name orgdt -Value 'C:\scripts\organizebydatetime.ps1'
Set-Alias -Name psf -Value 'C:\scripts\processfilter.ps1'
Set-Alias -Name wipe -Value 'C:\scripts\clearcurrentfolder.ps1'
Set-Alias -Name wipedownloads -Value 'C:\scripts\cleardownloads.ps1'
Set-Alias -Name wd -Value 'C:\scripts\cleardownloads.ps1'
Set-Alias -Name wiped -Value 'C:\scripts\cleardownloads.ps1'
Set-Alias -Name unzip -Value 'C:\scripts\unzip.ps1'
Set-Alias -Name uz -Value 'C:\scripts\unzip.ps1'
Set-Alias -Name extractall -Value 'C:\scripts\unzip.ps1'
Set-Alias -Name listnames -Value 'C:\scripts\createfilenamestxt.ps1'
Set-Alias -Name shutdown -Value 'C:\scripts\shutdown.ps1'
Set-Alias -Name sd -Value 'C:\scripts\shutdown.ps1'
Set-Alias -Name compressall -Value 'C:\scripts\CompressFiles.ps1'
Set-Alias -Name killall -Value 'C:\scripts\killall.ps1'
Set-Alias -Name ip -Value 'C:\scripts\ip.ps1'
Set-Alias -Name pnp -Value 'C:\scripts\showplugandplay.ps1'
Set-Alias -Name GetTrans -Value 'C:\scripts\GetCompiledTransFromFolder.ps1'
Set-Alias -Name gt -Value 'C:\scripts\GetCompiledTransFromFolder.ps1'
Set-Alias -Name get -Value 'C:\scripts\get.ps1'
Set-Alias -Name lget -Value 'C:\scripts\localget.ps1'
Set-Alias -Name time -Value 'C:\scripts\time.ps1'
Set-Alias -Name q -Value exit
Set-Alias -Name :q -Value exit
Set-Alias -Name cm -Value 'C:\scripts\startCMatrix.ps1'
Set-Alias -Name googler -Value 'C:\scripts\googler.ps1'
Set-Alias -Name g -Value 'C:\scripts\googler.ps1'
Set-Alias -Name luckygoogler -Value 'C:\scripts\lucky-googler.ps1'
Set-Alias -Name lg -Value 'C:\scripts\lucky-googler.ps1'
Set-Alias -Name buy -Value 'C:\scripts\buy.ps1'
Set-Alias -Name dwm -Value 'C:\scripts\rundwm.ps1'
Set-Alias -Name rdwm -Value 'C:\scripts\rebuilddwm.ps1'
Set-Alias -Name porn -Value 'C:\scripts\porn.ps1'
Set-Alias -Name dotnetversion -Value 'C:\scripts\getdotnetversion.ps1'
Set-Alias -Name c -Value 'C:\scripts\fcd.ps1'
Set-Alias -Name fcd -Value 'C:\scripts\fcd.ps1'
Set-Alias -Name fcdr -Value 'C:\scripts\fcd-recursive.ps1'
Set-Alias -Name jump -Value 'C:\scripts\jump.ps1'
Set-Alias -Name j -Value 'C:\scripts\jump.ps1'
Set-Alias -Name fii -Value 'C:\scripts\fii.ps1'
Set-Alias -Name i -Value 'C:\scripts\fii.ps1'
Set-Alias -Name killprocess -Value 'C:\scripts\killprocess.ps1'
Set-Alias -Name kp -Value 'C:\scripts\killprocess.ps1'
Set-Alias -Name fvim -Value 'C:\scripts\fvim.ps1'
Set-Alias -Name v -Value 'C:\scripts\fvim.ps1'
Set-Alias -Name frm -Value 'C:\scripts\frm.ps1'
Set-Alias -Name newscript -Value 'C:\scripts\newscript.ps1'
Set-Alias -Name newsc -Value 'C:\scripts\newscript.ps1'
Set-Alias -Name wifi -Value 'C:\scripts\wifi-connect.ps1'
Set-Alias -Name fcp -Value 'C:\scripts\fzfcopy.ps1'
Set-Alias -Name cop -Value 'C:\scripts\copy.ps1'
Set-Alias -Name cut -Value 'C:\scripts\cut.ps1'
Set-Alias -Name mv -Value 'C:\scripts\cut.ps1'
Set-Alias -Name bookmarks -Value 'C:\scripts\bookmarks\bookmarks.ps1'
Set-Alias -Name bm -Value 'C:\scripts\bookmarks\bookmarks.ps1'
Set-Alias -Name youtube -Value 'C:\scripts\search-youtube.ps1'
Set-Alias -Name yt -Value 'C:\scripts\youtube\search-youtube.ps1'
Set-Alias -Name ytch -Value 'C:\scripts\youtube\search-youtube-channels.ps1'
Set-Alias -Name ytc -Value 'C:\scripts\youtube\copy-youtube.ps1'
Set-Alias -Name lis -Value 'C:\scripts\list-installed-software.ps1'
Set-Alias -Name listsoftware -Value 'C:\scripts\list-installed-software.ps1'
Set-Alias -Name listtasks -Value 'C:\scripts\list-tasks.ps1'
Set-Alias -Name listservices -Value 'C:\scripts\list-services.ps1'
Set-Alias -Name remindme -Value 'C:\scripts\remind-me.ps1'
Set-Alias -Name inspectexe -Value 'C:\scripts\inspect-exe.ps1'
Set-Alias -Name iexe -Value 'C:\scripts\inspect-exe.ps1'
Set-Alias -Name crypto -Value 'C:\scripts\crypto.ps1'
Set-Alias -Name earthquakes -Value 'C:\scripts\earthquakes.ps1'
Set-Alias -Name news -Value 'C:\scripts\list-news.ps1'
Set-Alias -Name remindme -Value 'C:\scripts\remind-me.ps1'
Set-Alias -Name htop -Value 'C:\scripts\htop.ps1'
Set-Alias -Name weather -Value 'C:\scripts\weather.ps1'
Set-Alias -Name wth -Value 'C:\scripts\weather.ps1'
Set-Alias -Name killcortana -Value 'C:\scripts\killcortana.ps1'
Set-Alias -Name kcortana -Value 'C:\scripts\killcortana.ps1'
Set-Alias -Name deployun -Value 'C:\scripts\deploy-unify\deploy-unify.ps1'
Set-Alias -Name dun -Value 'C:\scripts\deploy-unify\deploy-unify.ps1'
Set-Alias -Name rnia -Value 'C:\scripts\deploy-unify\rename-all.ps1'
Set-Alias -Name share -Value 'C:\scripts\share-file.ps1'
Set-Alias -Name share-zip -Value 'C:\scripts\share-file-zipped.ps1'
Set-Alias -Name sh -Value 'C:\scripts\share-file.ps1'
Set-Alias -Name shz -Value 'C:\scripts\share-file-zipped.ps1'
Set-Alias -Name enable-powershell-remoting -Value 'C:\scripts\enable-powershell-remoting.ps1'
Set-Alias -Name epr -Value 'C:\scripts\enable-powershell-remoting.ps1'
Set-Alias -Name rem -Value 'C:\scripts\rem.ps1'
Set-Alias -Name s -Value 'C:\scripts\search-the-web\search-the-web.ps1'
Set-Alias -Name count -Value 'C:\scripts\count.ps1'
Set-Alias -Name extract -Value 'C:\scripts\extract.ps1'
Set-Alias -Name debloat -Value 'C:\scripts\debloat.ps1'

#Menus
Set-Alias -Name go -Value 'C:\scripts\fzfnavigator\go2.ps1'
Set-Alias -Name go2 -Value 'C:\scripts\fzfnavigator\go2.ps1'
Set-Alias -Name lsm -Value 'C:\scripts\menus\dir.ps1'

#Terminal messaging
Set-Alias -Name getfoundfilemessage -Value 'C:\scripts\getfilefound.ps1'

#Projects
Set-Alias -Name unify -Value 'C:\scripts\openunify.ps1'
Set-Alias -Name un -Value 'C:\scripts\openunify.ps1'
Set-Alias -Name drag -Value 'C:\scripts\opendragdrop.ps1'
Set-Alias -Name dr -Value 'C:\scripts\opendragdrop.ps1'
Set-Alias -Name build -Value 'C:\Scripts\build.ps1'
Set-Alias -Name debug -Value 'C:\Scripts\buildDebug.ps1'
Set-Alias -Name bump -Value 'C:\Scripts\AssemblyInfoUtil\bump.ps1'

#Dir Helpers
Set-Alias -Name scripts -Value 'C:\scripts\openscripts.ps1'
Set-Alias -Name sc -Value 'C:\scripts\openscripts.ps1'
Set-Alias -Name winrar -Value 'C:\Program Files\WinRAR\WinRAR.exe'
Set-Alias -Name wr -Value 'C:\Program Files\WinRAR\WinRAR.exe'
Set-Alias -Name desktop -Value 'C:\scripts\opendesktop.ps1'
Set-Alias -Name desk -Value 'C:\scripts\opendesktop.ps1'
Set-Alias -Name root -Value 'C:\scripts\openroot.ps1'
Set-Alias -Name r -Value 'C:\scripts\openroot.ps1'
Set-Alias -Name music -Value 'C:\scripts\openmusic.ps1'
Set-Alias -Name mus -Value 'C:\scripts\openmusic.ps1'
Set-Alias -Name images -Value 'C:\scripts\openimages.ps1'
Set-Alias -Name img -Value 'C:\scripts\openimages.ps1'
Set-Alias -Name im -Value 'C:\scripts\openimages.ps1'
Set-Alias -Name documents -Value 'C:\scripts\opendocuments.ps1'
Set-Alias -Name docs -Value 'C:\scripts\opendocuments.ps1'
Set-Alias -Name doc -Value 'C:\scripts\opendocuments.ps1'
Set-Alias -Name home -Value 'C:\scripts\openhome.ps1'
Set-Alias -Name h -Value 'C:\scripts\openhome.ps1'
Set-Alias -Name downloads -Value 'C:\scripts\opendownloads.ps1'
Set-Alias -Name dw -Value 'C:\scripts\opendownloads.ps1'
Set-Alias -Name dl -Value 'C:\scripts\opendownloads.ps1'
Set-Alias -Name powershell -Value 'C:\scripts\openpowershell.ps1'
Set-Alias -Name here -Value Get-Location
Set-Alias -Name cf -Value 'C:\scripts\opencf.ps1'
Set-Alias -Name dotfiles -Value 'C:\scripts\opendotfiles.ps1'
Set-Alias -Name tserver -Value 'C:\scripts\tserver.ps1'
Set-Alias -Name aliases -Value 'C:\scripts\aliases.ps1'
Set-Alias -Name al -Value 'C:\scripts\aliases.ps1'

#OpenAI
Set-Alias -Name psh -Value 'C:\scripts\Open-Ai\PS-Helper.ps1'
Set-Alias -Name alexa -Value 'C:\scripts\Open-Ai\alexa.ps1'

#For Fun
Set-Alias -Name matrix -Value 'C:\scripts\cmatrix.ps1'
Set-Alias -Name pozzi -Value 'C:\scripts\pozzigape.ps1'

#Audio  
Set-Alias -Name normalize-all -Value 'C:\scripts\sox\normalize-all.ps1'
Set-Alias -Name na -Value 'C:\scripts\sox\normalize-all.ps1'
Set-Alias -Name pac -Value 'C:\scripts\sox\run-py-audio-classification.ps1'

#Cams
Set-Alias -Name viewcam -Value 'C:\scripts\cameras\view_current_cam.ps1'
Set-Alias -Name cam -Value 'C:\scripts\cameras\view_current_cam.ps1'
